### ISSUE TITLE
Cake-Bootstrapper requires at least PowerShell Version 3

### ISSUE THREAD

**Issue by gep13** [cake-build/bootstrapper#11]
Just noticed this:

![image](https://cloud.githubusercontent.com/assets/1271146/5792282/ef49cd70-9f08-11e4-952c-08786140a9cd.png)

When testing the new Chocolatey Package.

Is this file required as part of the bootstrapper?  It is not a huge deal to include it, just wondered why it is there.

**Comment by gep13** [comment]
Never mind, just looking at the instructions for how to use this, and I see why it is required.  Ignore me :smile_cat:

**Comment by devlead** [comment]
Indeed ;) 
https://github.com/cake-build/bootstrapper/blob/master/src/Bootstrapper/Cake.Bootstrapper/Installer/InstallCommand.cs#L99

It's for the optional AppVeyor support.

**Comment by gep13** [comment]
Yip, I did notice one thing though, when trying to run Install-Cake, I was met with this:

![image](https://cloud.githubusercontent.com/assets/1271146/5792317/e6b121d4-9f0a-11e4-80db-7e417e479d35.png)

I have closed and re-opened the PowerShell session, but doesn't seem like that cmd-let is available.  Any thoughts on this one?

**Comment by devlead** [comment]
Did you run Chocolatey as administrator?

**Comment by gep13** [comment]
Yip, certainly did

Sent from my Windows Phone
________________________________

**Comment by patriksvensson** [comment]
Hmm. @devlead Does v0.0.5 work for you?

**Comment by patriksvensson** [comment]
@gep13 does a uninstall and then reinstall make it work?

**Comment by devlead** [comment]
It's latest version on chocolatey yet? if so haven't got a chance to try yet @patriksvensson , remembered I had to unusual manually from add/remove programs once.
Last version I tried worked without needing to restart PowerShell, which I needed with previous versions.

**Comment by patriksvensson** [comment]
The latest version is on Chocolatey. Approved today by @gep13 :smile:

**Comment by gep13** [comment]
Yup, it was me that approved it, but after approving it, I thought I would try it out as well, and that was when I noticed the second issue.

This was on a fresh installation of a Windows 7 Virtual Machine that I use for testing Chocolatey Packages in moderation.  The actual installation went fine, with no problems, but Module doesn't seem to be registered.

I tried a manual uninstallation through Add/Remove programs, and then another installation but same problem.

**Comment by patriksvensson** [comment]
Hmm, I install the package, and it says in Chocolatey that it installs version 0.0.5, but it's version 0.0.4 that gets installed. Downloading the MSI directly from the link in [tools\chocolateyInstall.ps1](https://chocolatey.org/packages/cake-bootstrapper) installs version 0.0.5.

Not really sure what's going on, but could you check what version that gets installed in the control panel?

**Comment by gep13** [comment]
Okay, so I have done a few tests, and these are my findings...

If I do a fresh install of version 0.0.4, I can confirm that this is what is installed in Add Remove Programs.

![image](https://cloud.githubusercontent.com/assets/1271146/5793721/6e01e0f2-9f46-11e4-93c0-3cda7591bdb3.png)

However, even with this version, I still can't run ```Install-Cake```.

![image](https://cloud.githubusercontent.com/assets/1271146/5793727/80c5e490-9f46-11e4-8809-af99ef9b6c12.png)

If I then do an update to 0.0.5, chocolatey correctly downloads that version's MSI, and runs it, however, the installed application doesn't get updated in Add Remove Programs.  I would have expected the MSI installer to first remove the old one, and replace with the new one.  If this doesn't happen, then you may need to extend the chocolateyInstall.ps1 file to detect if it is already installed, and remove it.

![image](https://cloud.githubusercontent.com/assets/1271146/5793733/aae24fe8-9f46-11e4-8efd-313bb7d06f06.png)

If I then do a fresh install of version 0.0.5, it correctly installs this version, as seen in Add Remove Programs:

![image](https://cloud.githubusercontent.com/assets/1271146/5793753/8005cf92-9f47-11e4-82ff-429c061ba5be.png)

But again, still no ```Install-Cake```

![image](https://cloud.githubusercontent.com/assets/1271146/5793755/97069b7c-9f47-11e4-9811-1bf34953bff6.png)

Any thoughts?

**Comment by devlead** [comment]
Tried a new clean WM and it didn't get available directly efter choco install, but when i started new PowerShell sesison
```
C:\temp> help Install-Cake

NAME
    Install-Cake

SYNTAX
    Install-Cake [-Source <string>] [-AppVeyor] [-GitIgnore]  [<CommonParameters>]


ALIASES
    None


REMARKS
    None

```

**Comment by gep13** [comment]
What OS are you using, and what version of Powershell are you using? I will try to match both of these and see if I can get it working.

Sent from my Windows Phone
________________________________

**Comment by devlead** [comment]
I've tried new VM's with Windows 10 & Windows 8.1 Enterprise (I had to start a new PowerShell session after choco install), also did a coco update on my laptop running Windows 10 and that worked.
Time for some sleep here, but will test some more tomorrow.

**Comment by gep13** [comment]
Hmm, ok, I was running on a Windows 7 VM, with PowerShell 2.  I wonder if this could be something to do with a dependency on a higher version of PowerShell, which would come in the box on both Windows 8 and Windows 10?  I have base VM's of each of these at home, so I will try to do a test on both of those later tonight.

**Comment by patriksvensson** [comment]
Is all service packs installed for the Windows 7 VM? Windows 7 got Powershell 3 support in SP1. If not, this might be a Powershell 2 incompatibility. I'm far from an expert on Powershell, so this might be a long shot :smile: 

Right now, we have a dependency on System.Managment.Automation version 6.1.7601.17515 which we retrieve from (NuGet)[https://www.nuget.org/packages/System.Management.Automation/].

**Comment by gep13** [comment]
Hmm, I will have to check that, I didn't think PowerShell came as an update in Service Packs, I thought you had to opt into it, using the correct version of the Windows Management Framework.  Chocolatey supports usage of PowerShell back to version 2, hence why I try to test on that version, so this was my assumption about Windows 7.  I will need to check this, and my Chocolatey testing might now be invalid :-)

**Comment by gep13** [comment]
Okay, looks like I am getting somewhere...

On my Windows 8.1 machine, it works happily:

![image](https://cloud.githubusercontent.com/assets/1271146/5807070/56df10b2-a017-11e4-9549-909493d9cff0.png)

However, on my Windows 7 machine, it doesn't:

![image](https://cloud.githubusercontent.com/assets/1271146/5807157/5d1d5668-a018-11e4-8bbb-a454c10d8cb6.png)

If I do:

```choco install powershell -Version 3.0.20121027```

Then things start working.  

![image](https://cloud.githubusercontent.com/assets/1271146/5807328/0cc065fa-a01a-11e4-93f2-76d8e04b1b6c.png)

So looks like Cake Bootstrapper has a dependency on at least PowerShell 3. That could be because of the Automation dependency that you have.

**Comment by patriksvensson** [comment]
Hmm, this is not good. I'll try to see if I can fix it tomorrow after work. 
Thanks for the invaluable work you've done here! I'm grateful! :smile:

**Comment by gep13** [comment]
Not a problem at all, happy to help :smile: 

Your Chocolatey package could simply take a dependency on PowerShell 3, but that is "tricky" for a number of reasons.  The installation of PowerShell 3 requires a reboot in order for it to take, so taking that dependency directly in your nuspec likely won't work, as the registration of your Module wouldn't succeed until after the reboot.  If you threw boxstarter into the mix, then it could handle the reboot requirement, but not everyone will be using that.  If you can't get around the dependency, you could add it into your WiX installer, but that is another rabbit hole.

So, not sure...  Hopefully you can come up with something.

**Comment by c0bra** [comment]
I get the same cmdlet not recognized error on Win7 with Powershell v4. I have tried installing/uninstalling with elevated privileges but no joy.

**Comment by molehillrocker** [comment]
I applied this fix [450b315d](https://github.com/cake-build/cake/commit/450b315db35e3df5ad625ae1b6be91ab41d04bf8) to the bootstrapper script manually and now it works nicely on our build server where PowerShell v2.0 is installed. :see_no_evil: 

Should I make a PR for it (I'm not sure about possible side effects)?

**Comment by devlead** [comment]
@molehillrocker sorry for not getting back to you earlier, sure send us an PR and we'll have a look at it.

**Comment by molehillrocker** [comment]
Here it is: #23

**Comment by gep13** [comment]
@devlead @patriksvensson  Wow, I had forgotten all about this issue!

Closing to go ahead and close it out though :smile:
