### ISSUE TITLE
Chocolatey installer not working

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/bootstrapper#15]
I installed cake-bootstrapper from Chocolatey, closed the console and opened a new PowerShell console, but the Install-Cake command isn't recognized:

```
Install-Cake : The term 'Install-Cake' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

(I'm on Windows 10)

**Comment by thomaslevesque** [comment]
Cloning and building myself doesn't work either:
```
D:\Docs\GitHub\Cake-Bootstrapper [master]> .\build.ps1
Installing 'Cake 0.3.2'.
Installing 'WiX.Toolset 3.9.1006.0'.
Successfully installed 'Cake 0.3.2'.
Successfully installed 'WiX.Toolset 3.9.1006.0'.
Installing 'xunit.runners 2.0.0-beta5-build2785'.
Successfully installed 'xunit.runners 2.0.0-beta5-build2785'.
Using nightly build of Roslyn.
Checking what the latest version of Roslyn is...
The latest Roslyn version is 1.1.0-beta1-20150731-02.
Downloading and installing Roslyn...
Installing packages...
Downloading package Microsoft.CodeAnalysis.Scripting.CSharp (1.1.0-beta1-20150731-02)...
Downloading package Microsoft.CodeAnalysis.CSharp (1.1.0-beta1-20150731-02)...
Copying files...
Copying Microsoft.CodeAnalysis.dll...
Copying Microsoft.CodeAnalysis.Scripting.CSharp.dll...
Copying Microsoft.CodeAnalysis.Scripting.dll...
Error: Could not find file.
```

**Comment by devlead** [comment]
Did you install as admin? See if Cake is present under Windows installed programs, uninstall via Chocolatey and if it is still there then manually uninstall and then try again. Must be installed from an admin PowerShell prompt.

**Comment by thomaslevesque** [comment]
@devlead, yes, I ran Chocolatey as admin.

Actually, I just realized that the Install-Cake command is available in admin PS prompts, but not in normal ones.

**Comment by devlead** [comment]
@thomaslevesque  I see It's using an old version of Cake, probably using an depreciated version of Roslyn. Me, @patriksvensson or someone via PR will take a look at upgrading it to latest dependencies.

**Comment by devlead** [comment]
@thomaslevesque ah I see, might be some profile issue then, traveling so can't debug now, if no one addresses before I'll take a look post weekend and get back to you.

**Comment by thomaslevesque** [comment]
@devlead OK, thanks.

**Comment by patriksvensson** [comment]
I'll fix this tomorrow :smile:

**Comment by patriksvensson** [comment]
You should be able to build it now without problem.

**Comment by thomaslevesque** [comment]
Yes, it works. Thanks!
