### ISSUE TITLE
VSO Build fails on where.exe nuget.exe without result

### ISSUE THREAD

**Issue by DavidDeSloovere** [cake-build/bootstrapper#18]
I'm trying out CAKE in the new team build (vNext) and a build agent that runs on prem. The build step (a default powershell step) calls build.ps1 and although the build.ps1 and cake have run successfully, it shows up as failed.

I've tracked it down to this line, where *where.exe* is used to find *nuget.exe*. When I comment out this part of build.ps1, it works fine.
https://github.com/cake-build/bootstrapper/blob/master/res/scripts/build.ps1#L94

In the output, sent back to VSO from the agent I see this:

    2015-09-09T15:05:06.0383514Z ##[error]Task PowerShell failed. This caused the job to fail. Look at the logs for the task for more details.

Scrolling up the log I find:

    2015-09-09T15:04:51.1045929Z VERBOSE: Trying to find nuget.exe in path...
    2015-09-09T15:04:51.2451719Z ##[error]INFO: Could not find files for the given pattern(s).
    

Because where.exe does not find a match it returns "INFO: Could not find files for the given pattern(s).". Together with that message an exit code of 1 is returned that indicates an *error*. 

    C:\Windows\system32>where.exe
    ...
    NOTE: The tool returns an error level of 0 if the search is
                successful, of 1 if the search is unsuccessful and
                of 2 for failures or errors.

Forcing $LASTEXITCODE to zero, right after the call to *where.exe* does not work.
I'm not a powershell expert, but refactoring this to use *Get-ChildItem* with both the local folder and the PATH environment variable seems like a good solution. http://superuser.com/a/675838
I'd be happy to contribute.

**Comment by devlead** [comment]
Yeah just splitting $env:path, joining and testing paths should replace where.

If you'd like to send a PR go ahead:+1:

**Comment by patriksvensson** [comment]
A PR is always welcome :smile: :+1:

**Comment by devlead** [comment]
Closed via #19
