### ISSUE TITLE
bootstrapper for mono on mac / linux

### ISSUE THREAD

**Issue by naveensrinivasan** [cake-build/bootstrapper#20]
It would be nice to have a bootstrapper for mono on the mac. Another reason could also be because of CoreClr coming to other platforms.

**Comment by devlead** [comment]
Hi,

There's a minimal bootstrapper avail for MacOSX, Linux and Windows here:
http://cakebuild.net/docs/tutorials/setting-up-a-new-project

**Comment by patriksvensson** [comment]
@devlead The bootstrapper for os x and linux is as capable as the PowerShell one if I'm not mistaken :smile:

**Comment by devlead** [comment]
@patriksvensson details ;)

**Comment by naveensrinivasan** [comment]
Thanks. Got it.
