### ISSUE TITLE
Use the 3.X NuGet CLI

### ISSUE THREAD

**Issue by michael-wolfenden** [cake-build/bootstrapper#22]
Wanted to start a discussion on whether we should start using the 3.X NuGet CLI.

The NuGet team has made it available at - http://dist.nuget.org/win-x86-commandline/latest/nuget.exe
(see https://docs.nuget.org/consume/installing-nuget)

Unfortunately, the boostrapper is currently not working with the latest 3.X CLI (3.2) due to a bug with -ExcludeVersion (https://github.com/NuGet/Home/issues/1473) which is preventing the cake exe from being found, but this is an easy fix.

Thoughts?

**Comment by patriksvensson** [comment]
@michael-wolfenden I think it's a good idea to upgrade the bootstrapper, but not now. I would rather wait until the `ExcludeVersion` works as expected. If someone want to use NuGet 3.X now, it wouldn't be that difficult to change this themselves.

I think we wait a little longer, but I appreciate that you brought this to my attention :smile:

**Comment by michael-wolfenden** [comment]
@patriksvensson Just a heads up, Nuget CLI v3.3 has been released and fixes the ExcludeVersion (https://github.com/NuGet/Home/issues/1473) bug. 

I can confirm that replacing http://nuget.org/nuget.exe with http://dist.nuget.org/win-x86-commandline/latest/nuget.exe in the bootstrapper now works.

**Comment by patriksvensson** [comment]
@michael-wolfenden Good to know! Thanks for the heads up! Will get back to this after work and take a look.

**Comment by devlead** [comment]
Bootstrappers now use V3.
