### ISSUE TITLE
Cake is Verbose by default, Verbosity setting (largely) ignored by MSBuild

### ISSUE THREAD

**Issue by ericwj** [cake-build/bootstrapper#28]
Can you please fix http://cakebuild.net/bootstrapper/windows to have `[string]$Verbosity = "Normal"` as opposed to `[string]$Verbosity = "Verbose"` please? Or perhaps even Quiet?

My build takes over 6 minutes on Release/Verbose and over 3 on Debug/Quiet, however in Visual Studio the build takes maybe 10 seconds. On Quiet a build is still burrying me with verbose messages in cyan `14>CoreCompile` etcetera and gray, so I think MSBuild isn't being told to be verbose or not - or at least not quite effectively.

Separately perhaps there is some kind of issue with Console Output in DNX, or on Windows 10 over RDP, or with the 16px font on a 4k screen - I'm not quite sure, but the console output is very slow for me and that's not a Cake issue. Yet Cake just writes too much

Honestly I just copied over [the minimal, convention based cake script](https://github.com/cake-build/bootstrapper/blob/master/res/scripts/build.cake) and trying to build my solution with Cake for the first time, so I didn't figure out so quickly how to fix the script to pass the verbosity setting to MSBuild, but perhaps its quite very reasonable and desired to be right expecting that the verbosity setting affects MSBuild? And that Verbose is not the convention/default?

**Comment by patriksvensson** [comment]
@ericwj Both the bootstrapper and the minimal conventioned based cake script that you talk about is just there as an example to get started. You are supposed to use that as a starting point and tailor it to your build needs. We won't be changing the default verbosity for the Cake scripts, but it's easy to change it yourself in your bootstrapper script after you've downloaded it.

Cake's verbosity has nothing to do with MSBuild even if it feels that way and verbosity wise they do not map 1:1 (diagnostic verbosity in MSBuild for a complete empty project will output about 200 kb of logs). MSBuild's logging also affect the build time. You can change the verbosity of MSBuild by setting the verbosity flag on the MSBuild alias.

```csharp
MSBuild("./MyProject.sln", new MSBuildSettings()
  .SetVerbosity(Verbosity.Minimal));
```

**Comment by ericwj** [comment]
Thanks, I'll use that snippet till I get to diving deeper into cake. Well, I'm talking about the build.ps1 that downloads bootstrapping cake. What my cake does is up to me, I agree. My idea is just verbose isn't such a great default. It'd be easy to override in a CI script or so, but interactively, it's clutter most of the time and I mean 5 9's of the time. Yet doing it interactively now requires to type yet another argument every time.

**Comment by gep13** [comment]
@ericwj as you might have noticed, we are moving away from recommending the use of this Bootstrapper project, in favour of a simpler approach in the form of this repository:

https://github.com/cake-build/resources

If required, please feel free to bring this issue up again there.  Closing for now.
