### ISSUE TITLE
Test-Path fails for empty strings from the split PATH variable

### ISSUE THREAD

**Issue by BenMagyar** [cake-build/bootstrapper#34]
When checking for the NuGet.exe, splitting the PATH variable can pass along empty strings to the `Test-Path` call; however, `Test-Path` does not accept empty strings. Easiest to just add a check to filter down to only non-empty strings.

**Comment by gep13** [comment]
This has been re-opened in new repository over here: https://github.com/cake-build/resources/pull/5

So closing this issue.
