### ISSUE TITLE
Add .Description() for each Task of the *.cake files in the scripts folder

### ISSUE THREAD

**Issue by bravecobra** [cake-build/bootstrapper#37]
Adding a description to describe a task, would help new developers to understand what is going on when running cake and have an understanding of what a cake script is doing. It would also show these when running with -showdescription which let's you choose the appropriate target to run.

**Comment by gep13** [comment]
@bravecobra can you have a look at #38 and let me know if this is what you were thinking?

**Comment by bravecobra** [comment]
Yes, that would pretty much do it.
