### ISSUE TITLE
Cannot use the -ScriptArgs option

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/bootstrapper#39]
The `-ScriptArgs` parameter of the bootstrapper doesn't seem to work. I installed the bootstrapper as explained [here](http://cakebuild.net/docs/tutorials/setting-up-a-new-project), and tried the following commands (and a few other variants):

```
.\build.ps1 -ScriptArgs foobar
.\build.ps1 build.cake -ScriptArgs foobar
.\build.ps1 -Script build.cake -ScriptArgs foobar
```

Every time, I got this error:

> More than one build script specified.
> 
> Could not find a build script to execute.
> Either the first argument must the build script's path,
> or build script should follow default script name conventions.
> Usage: Cake.exe [build-script] [-verbosity=value]
>                [-showdescription] [-dryrun] [..]
> ...

**Comment by patriksvensson** [comment]
@thomaslevesque The `ScriptArgs` parameter is something that bundles the remaining arguments and passes them on as they are.

Try passing it like this:

```
.\build.ps1 --foobar=true
```

**Comment by thomaslevesque** [comment]
Ah, thanks! I couldn't figure out the proper syntax
